# File di configurazione per Netlify

[build]
  # Specifica la cartella che contiene le funzioni serverless.
  functions = "netlify/functions/"
  
  [build.environment]
    # Imposta una versione di Node.js stabile (LTS) per l'intero ambiente di build.
    # Questo risolve l'errore di build.
    NODE_VERSION = "18"
